"""
Held-out opponent population.

None of these archetypes appear in the original research log's set of nine
(always-long, always-short, abstainer, momentum, minority-chaser, herd-follower,
period-2, random, budget-aware). They are written as plausible independent
submissions by other teams, and the strategy under test has never been run
against any of them.

Rooms are generated by random sampling over compositions and sizes rather than
hand-picked, which is the main defence against scoring a strategy on the same
scenarios that shaped it.

All agents keep incremental state so a 365-day run is linear, not quadratic.
"""

from __future__ import annotations

from engine import START_PRICE, Agent


# ----------------------------------------------------------- new archetypes


class EWMAContrarian(Agent):
    """Exponentially weighted view of the crowd, faded once it is lopsided."""
    name = "ewma-contrarian"

    def __init__(self, alpha=0.2, thresh=0.15):
        self.alpha, self.thresh = alpha, thresh

    def reset(self, rng):
        self.rng = rng
        self.s = 0.0

    def observe(self, prices, moves, my_action):
        m = moves[-1]
        lean = 1.0 if m < 0 else (-1.0 if m > 0 else 0.0)  # +1 = crowd long
        self.s = (1 - self.alpha) * self.s + self.alpha * lean

    def act(self, prices, moves, day):
        if len(moves) < 3:
            return 0
        if self.s > self.thresh:
            return -1
        if self.s < -self.thresh:
            return 1
        return 0


class FictitiousPlay(Agent):
    """Empirical frequency of crowd-long, best response against the 8/13 line."""
    name = "fictitious-play"

    def reset(self, rng):
        self.rng = rng
        self.L = 0
        self.S = 0

    def observe(self, prices, moves, my_action):
        m = moves[-1]
        if m < 0:
            self.L += 1
        elif m > 0:
            self.S += 1

    def act(self, prices, moves, day):
        tot = self.L + self.S
        if tot < 5:
            return 0
        return 1 if self.L / tot < 8 / 13 else -1


class NoisyRegimeContrarian(Agent):
    """
    A partially-crowded competitor: same family as the candidate but a different
    window, no confidence discount, and action noise. Models other teams
    reaching a similar-but-not-identical conclusion.
    """
    name = "noisy-regime-contrarian"

    def __init__(self, window=60, noise=0.15):
        self.window, self.noise = window, noise

    def reset(self, rng):
        self.rng = rng
        self.pairs = []  # (regime, outcome), trimmed to window

    def observe(self, prices, moves, my_action):
        m = len(moves)
        if m >= 2:
            prev = moves[m - 2]
            r = -1 if prev < 0 else (1 if prev > 0 else 0)
            self.pairs.append((r, moves[m - 1]))
            if len(self.pairs) > self.window:
                self.pairs.pop(0)

    def act(self, prices, moves, day):
        if len(moves) < 6:
            return 0
        if self.rng.random() < self.noise:
            return int(self.rng.integers(-1, 2))
        cur = moves[-1]
        reg = -1 if cur < 0 else (1 if cur > 0 else 0)
        sample = [o for r, o in self.pairs if r == reg]
        if len(sample) < 3:
            return 0
        mean = sum(sample) / len(sample)
        return 1 if mean > 0 else (-1 if mean < 0 else 0)


class PriceAnchor(Agent):
    """Treats the ticket as cheap or dear relative to where it started."""
    name = "price-anchor"

    def __init__(self, ratio=0.6):
        self.ratio = ratio

    def act(self, prices, moves, day):
        return 1 if prices[-1] < self.ratio * START_PRICE else -1


class FloorCamper(Agent):
    """Sits out until the ticket is near the floor, then holds the free option."""
    name = "floor-camper"

    def __init__(self, trigger=30_000):
        self.trigger = trigger

    def act(self, prices, moves, day):
        return 1 if prices[-1] <= self.trigger else 0


class WindowFollower(Agent):
    """Joins whichever side won most often over a short lookback."""
    name = "window-follower"

    def __init__(self, w=3):
        self.w = w

    def act(self, prices, moves, day):
        win = moves[-self.w:]
        if not win:
            return 0
        longs = sum(1 for m in win if m < 0)
        shorts = sum(1 for m in win if m > 0)
        if longs > shorts:
            return 1
        if shorts > longs:
            return -1
        return 0


class EpsilonGreedy(Agent):
    """Learns which side has paid better, with exploration."""
    name = "epsilon-greedy"

    def __init__(self, eps=0.1):
        self.eps = eps

    def reset(self, rng):
        self.rng = rng
        self.tot = 0

    def observe(self, prices, moves, my_action):
        self.tot += moves[-1]

    def act(self, prices, moves, day):
        if len(moves) < 4 or self.rng.random() < self.eps:
            return int(self.rng.integers(-1, 2))
        if self.tot > 0:
            return 1
        if self.tot < 0:
            return -1
        return 0


class StreakBreaker(Agent):
    """Fades a run of same-direction days."""
    name = "streak-breaker"

    def __init__(self, n=3):
        self.n = n

    def reset(self, rng):
        self.rng = rng
        self.sided = []

    def observe(self, prices, moves, my_action):
        if moves[-1] != 0:
            self.sided.append(moves[-1])
            if len(self.sided) > 8:
                self.sided.pop(0)

    def act(self, prices, moves, day):
        if len(self.sided) < self.n:
            return 0
        last = self.sided[-self.n:]
        if all(m < 0 for m in last):
            return -1
        if all(m > 0 for m in last):
            return 1
        return 0


class AlternatorK(Agent):
    """Fixed cycle of period k with an offset, so copies desynchronise."""
    name = "alternator-k"

    def __init__(self, k=3, offset=0):
        self.k, self.offset = k, offset

    def act(self, prices, moves, day):
        phase = (day + self.offset) % self.k
        return 1 if phase == 0 else (-1 if phase == 1 else 0)


class PanicStopper(Agent):
    """Holds long until drawdown exceeds a limit, then stops trading for good."""
    name = "panic-stopper"

    def __init__(self, limit=60_000):
        self.limit = limit

    def reset(self, rng):
        self.rng = rng
        self.pnl = 0
        self.dead = False

    def observe(self, prices, moves, my_action):
        self.pnl += my_action * moves[-1]
        if self.pnl <= -self.limit:
            self.dead = True

    def act(self, prices, moves, day):
        return 0 if self.dead else 1


class LateEntrant(Agent):
    """Waits, watches, then commits long for the rest of the year."""
    name = "late-entrant"

    def __init__(self, start=90):
        self.start = start

    def act(self, prices, moves, day):
        return 1 if day >= self.start else 0


class BayesianBeta(Agent):
    """Beta posterior on the crowd-long rate, acted on against the 8/13 line."""
    name = "bayesian-beta"

    def __init__(self, a=1.0, b=1.0):
        self.a, self.b = a, b

    def reset(self, rng):
        self.rng = rng
        self.L = 0
        self.S = 0

    def observe(self, prices, moves, my_action):
        if moves[-1] < 0:
            self.L += 1
        elif moves[-1] > 0:
            self.S += 1

    def act(self, prices, moves, day):
        if self.L + self.S < 3:
            return 0
        post = (self.a + self.L) / (self.a + self.b + self.L + self.S)
        return 1 if post < 8 / 13 else -1


class AntiContrarian(Agent):
    """Joins the apparent winner. Some teams will read the rules backwards."""
    name = "anti-contrarian"

    def act(self, prices, moves, day):
        if not moves or moves[-1] == 0:
            return 0
        return 1 if moves[-1] > 0 else -1


class BiasedRandom(Agent):
    """Seeded randomness with a room-specific long bias."""
    name = "biased-random"

    def __init__(self, p_long=0.4, p_flat=0.2):
        self.p_long, self.p_flat = p_long, p_flat

    def act(self, prices, moves, day):
        if self.rng.random() < self.p_flat:
            return 0
        return 1 if self.rng.random() < self.p_long else -1


class ThresholdHerder(Agent):
    """Stays out until one side is clearly winning, then piles on."""
    name = "threshold-herder"

    def __init__(self, w=10, thresh=0.7):
        self.w, self.thresh = w, thresh

    def act(self, prices, moves, day):
        win = [m for m in moves[-self.w:] if m != 0]
        if len(win) < max(1, self.w // 2):
            return 0
        frac_long = sum(1 for m in win if m < 0) / len(win)
        if frac_long >= self.thresh:
            return 1
        if 1 - frac_long >= self.thresh:
            return -1
        return 0


HELD_OUT = [
    EWMAContrarian, FictitiousPlay, NoisyRegimeContrarian, PriceAnchor,
    FloorCamper, WindowFollower, EpsilonGreedy, StreakBreaker, AlternatorK,
    PanicStopper, LateEntrant, BayesianBeta, AntiContrarian, BiasedRandom,
    ThresholdHerder,
]


def _instantiate(cls, rng):
    """Randomise each archetype's own parameters so rooms are not identical."""
    if cls is EWMAContrarian:
        return cls(alpha=float(rng.uniform(0.05, 0.4)), thresh=float(rng.uniform(0.05, 0.3)))
    if cls is NoisyRegimeContrarian:
        return cls(window=int(rng.integers(20, 120)), noise=float(rng.uniform(0.05, 0.35)))
    if cls is PriceAnchor:
        return cls(ratio=float(rng.uniform(0.35, 0.85)))
    if cls is FloorCamper:
        return cls(trigger=int(rng.integers(21_000, 45_000)))
    if cls is WindowFollower:
        return cls(w=int(rng.integers(2, 8)))
    if cls is EpsilonGreedy:
        return cls(eps=float(rng.uniform(0.02, 0.25)))
    if cls is StreakBreaker:
        return cls(n=int(rng.integers(2, 5)))
    if cls is AlternatorK:
        return cls(k=int(rng.integers(2, 6)), offset=int(rng.integers(0, 6)))
    if cls is PanicStopper:
        return cls(limit=int(rng.integers(30_000, 200_000)))
    if cls is LateEntrant:
        return cls(start=int(rng.integers(20, 180)))
    if cls is BayesianBeta:
        return cls(a=float(rng.uniform(0.5, 3)), b=float(rng.uniform(0.5, 3)))
    if cls is BiasedRandom:
        return cls(p_long=float(rng.uniform(0.2, 0.8)), p_flat=float(rng.uniform(0.0, 0.5)))
    if cls is ThresholdHerder:
        return cls(w=int(rng.integers(5, 25)), thresh=float(rng.uniform(0.55, 0.9)))
    return cls()


def random_room(rng, min_size=6, max_size=45):
    """
    Sample a room: size uniform over a wide range, composition from a Dirichlet
    over the held-out archetypes with a varying concentration, so some rooms are
    dominated by one behaviour and others are evenly mixed.
    """
    size = int(rng.integers(min_size, max_size + 1))
    conc = float(rng.choice([0.15, 0.4, 1.0, 3.0]))
    weights = rng.dirichlet([conc] * len(HELD_OUT))
    picks = rng.choice(len(HELD_OUT), size=size, p=weights)
    return [_instantiate(HELD_OUT[i], rng) for i in picks]
